os: linux
dist: bionic
language: c

services:
  - docker

addons:
 snaps:
   - name: aws-cli
     confinement: classic

env:
  global:
    - VERSION="build-$TRAVIS_BUILD_NUMBER"
  jobs:
    - UBUNTU=16.04
    - UBUNTU=18.04

script:
  - make --no-builtin-rules build
  - make --no-builtin-rules units
  - make --no-builtin-rules publish
  - make --no-builtin-rules integration

deploy:
  provider: script
  on:
    branch: master
  skip_cleanup: true
  script:
    - VERSION=latest make --no-builtin-rules release
